include theos/makefiles/common.mk

APPLICATION_NAME = Talkative
Talkative_FILES = main.m TalkativeApplication.mm RootViewController.mm
Talkative_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
